name: name_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 👉 스캐너 앱에 필요한 패키지 추가
  camera: ^0.10.0+3
  image_picker: ^1.0.3
  image_cropper: ^5.0.0
  google_mlkit_text_recognition: ^0.3.0
  path_provider: ^2.0.15
  drift: ^2.8.3
  drift_sqflite: ^0.4.1
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
